export const LOAD_FILTERED_REVIEWS = 'reviews/LOAD_FILTERED_REVIEWS';
export const LOAD_FILTERED_REVIEWS_SUCCESS =
  'reviews/LOAD_FILTERED_REVIEWS_SUCCESS';
export const LOAD_FILTERED_REVIEWS_ERROR =
  'reviews/LOAD_FILTERED_REVIEWS_ERROR';
